export enum RequestStatusPermissionEnum {
    CAN_UPDATE_MAINTENANCE_REQUEST_STATUS = 'CAN_UPDATE_MAINTENANCE_REQUEST_STATUS',
    CAN_VIEW_ALL_STATUSES_FOR_REQUEST = 'CAN_VIEW_ALL_STATUSES_FOR_REQUEST',
    CAN_VIEW_SINGLE_STATUS_FOR_REQUEST = 'CAN_VIEW_SINGLE_STATUS_FOR_REQUEST',
  }
  