export enum RequestStatusEnum {
    SUBMITTED = 'SUBMITTED',
    VERIFIED = 'VERIFIED',
    REVIEWED = 'REVIEWED',
    MOVED_TO_DEPARTMENT = 'MOVED_TO_DEPARTMENT',
    ASSIGNED_TO_PERSON = 'ASSIGNED_TO_PERSON',
    SCHEDULED_FOR_MAINTENANCE = 'SCHEDULED_FOR_MAINTENANCE',
    DONE = 'DONE',
    INFO_REQUESTED_FROM_USER = 'INFO_REQUESTED_FROM_USER',
    CONFIRMATION_REQUIRED_FROM_USER = 'CONFIRMATION_REQUIRED_FROM_USER'
}
