export enum MaintenanceRequestPermissionEnum {
  CAN_CREATE_MAINTENANCE_REQUEST = 'CAN_CREATE_MAINTENANCE_REQUEST',
  CAN_VIEW_ALL_MAINTENANCE_REQUESTS = 'CAN_VIEW_ALL_MAINTENANCE_REQUESTS',
  CAN_VIEW_ASSIGNED_TO_ME_MAINTENANCE_REQUESTS = 'CAN_VIEW_ASSIGNED_TO_ME_MAINTENANCE_REQUESTS',
  CAN_VIEW_MY_MAINTENANCE_REQUESTS = 'CAN_VIEW_MY_MAINTENANCE_REQUESTS',
  CAN_VIEW_MY_DEPARTMENT_MAINTENANCE_REQUESTS = 'CAN_VIEW_MY_DEPARTMENT_MAINTENANCE_REQUESTS',
  CAN_VIEW_MAINTENANCE_REQUEST_BY_ID = 'CAN_VIEW_MAINTENANCE_REQUEST_BY_ID',
  CAN_UPDATE_MAINTENANCE_REQUEST = 'CAN_UPDATE_MAINTENANCE_REQUEST',
  CAN_DELETE_MAINTENANCE_REQUEST = 'CAN_DELETE_MAINTENANCE_REQUEST',
  CAN_SEARCH_MAINTENANCE_REQUESTS = 'CAN_SEARCH_MAINTENANCE_REQUESTS',
  CAN_SEARCH_MAINTENANCE_REQUESTS_BY_ASSIGNED_PERSON_IDS = 'CAN_SEARCH_MAINTENANCE_REQUESTS_BY_ASSIGNED_PERSON_IDS',
  CAN_SEARCH_MAINTENANCE_REQUESTS_BY_REQUEST_TYPE_IDS = 'CAN_SEARCH_MAINTENANCE_REQUESTS_BY_REQUEST_TYPE_IDS',
  CAN_SEARCH_MAINTENANCE_REQUESTS_BY_HANDLING_DEPARTMENT_ID = 'CAN_SEARCH_MAINTENANCE_REQUESTS_BY_HANDLING_DEPARTMENT_ID',
  CAN_SEARCH_MAINTENANCE_REQUESTS_BY_REQUESTER_ID = 'CAN_SEARCH_MAINTENANCE_REQUESTS_BY_REQUESTER_ID',
  CAN_SEARCH_MAINTENANCE_REQUESTS_BY_CONFIRMATION_STATUS = 'CAN_SEARCH_MAINTENANCE_REQUESTS_BY_CONFIRMATION_STATUS',
  CAN_SEARCH_MAINTENANCE_REQUESTS_BY_VERIFICATION_STATUS = 'CAN_SEARCH_MAINTENANCE_REQUESTS_BY_VERIFICATION_STATUS',
  CAN_SEARCH_MAINTENANCE_REQUESTS_BY_VERIFIED_BY_ID = 'CAN_SEARCH_MAINTENANCE_REQUESTS_BY_VERIFIED_BY_ID',
  CAN_SEARCH_MAINTENANCE_REQUESTS_BY_PRIORITY = 'CAN_SEARCH_MAINTENANCE_REQUESTS_BY_PRIORITY',
}

/**
 * The DB command to populate the above to the Permission DB
INSERT INTO permissions (name, description) VALUES
('CAN_CREATE_MAINTENANCE_REQUEST', 'Permission to create a new maintenance request'),
('CAN_VIEW_ALL_MAINTENANCE_REQUESTS', 'Permission to view all maintenance requests'),
('CAN_VIEW_ASSIGNED_TO_ME_MAINTENANCE_REQUESTS', 'Permission to view maintenance requests assigned to the current user'),
('CAN_VIEW_MY_MAINTENANCE_REQUESTS', 'Permission to view maintenance requests created by the current user'),
('CAN_VIEW_MY_DEPARTMENT_MAINTENANCE_REQUESTS', 'Permission to view maintenance requests assigned to the current user\'s department'),
('CAN_VIEW_MAINTENANCE_REQUEST_BY_ID', 'Permission to view a maintenance request by its ID'),
('CAN_UPDATE_MAINTENANCE_REQUEST', 'Permission to update a maintenance request by its ID'),
('CAN_DELETE_MAINTENANCE_REQUEST', 'Permission to delete a maintenance request by its ID'),
('CAN_SEARCH_MAINTENANCE_REQUESTS', 'Permission to search maintenance requests'),
('CAN_SEARCH_MAINTENANCE_REQUESTS_BY_ASSIGNED_PERSON_IDS', 'Permission to search maintenance requests by assigned person IDs'),
('CAN_SEARCH_MAINTENANCE_REQUESTS_BY_REQUEST_TYPE_IDS', 'Permission to search maintenance requests by request type IDs'),
('CAN_SEARCH_MAINTENANCE_REQUESTS_BY_HANDLING_DEPARTMENT_ID', 'Permission to search maintenance requests by handling department ID'),
('CAN_SEARCH_MAINTENANCE_REQUESTS_BY_REQUESTER_ID', 'Permission to search maintenance requests by requester ID'),
('CAN_SEARCH_MAINTENANCE_REQUESTS_BY_CONFIRMATION_STATUS', 'Permission to search maintenance requests by confirmation status'),
('CAN_SEARCH_MAINTENANCE_REQUESTS_BY_VERIFICATION_STATUS', 'Permission to search maintenance requests by verification status'),
('CAN_SEARCH_MAINTENANCE_REQUESTS_BY_VERIFIED_BY_ID', 'Permission to search maintenance requests by verified by ID'),
('CAN_SEARCH_MAINTENANCE_REQUESTS_BY_PRIORITY', 'Permission to search maintenance requests by priority');
 */